### ISSUE TITLE
Unable to compile the release

### ISSUE THREAD

**Issue by Deadlyelder** [AaltoAsia/O-MI-Authorization#6]
Hello,

The staged release of the module v1.0.0 has issue during execution. For instance, if you run the `sbt run` on the release then the following error(s) is thrown

```bash
[error] java.lang.RuntimeException: No main class detected.
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$4(Defaults.scala:1179)
[error] 	at scala.Option.getOrElse(Option.scala:121)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$3(Defaults.scala:1179)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / bgRun) No main class detected.
```

On the other hand, if you are are at the master branch and compile, it works flawlessly. Might need to be checked.

Regards.

**Comment by TK009** [comment]
Hi,

Which package did you download?

The release is supposed to be run with `./bin/o-mi-authorization` startup script unless you downloaded the *"Source code (zip)"*. I added some extra instructions to clarify this in readme and release notes.

I hope this helps.
